name: getx_clean
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^5.0.1
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  retrofit: ^4.0.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.0.18
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.1
  json_serializable: ^6.6.1
  retrofit_generator: ^5.0.0
  build_runner: ^2.3.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
